[project]
name = "math-dataset"
version = "0.1.0"
description = "Math dataset processing and solving tools"
authors = [
    {name = "Xianglong Hu", email = "hxianglong@gmail.com"},
    {name = "Xingyue Huang", email = "xingyue.huang@cs.ox.ac.uk"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "datasets>=2.14.0",
    "pandas>=2.2.0",
    "numpy>=1.26.0",
    "sympy>=1.12",
    "pillow>=10.2.0",
    "camel-ai>=0.2.70",
    "requests-oauthlib>=1.3.1",
    "openai>=1.0.0",
    "python-dotenv>=1.0.1",
    "gradio>=4.13.0",
    "colorlog>=6.9.0",
    "colorama>=0.4.6",
    "math-verify>=0.6.0",
    "vllm>=0.7.3",
    "tabulate>=0.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
